name: grapcoin
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  change_app_package_name: ^1.1.0
  firebase_auth: ^4.7.1
  riverpod: ^2.3.6
  flutter_riverpod: ^2.3.6
  dio: ^5.3.0
  riverpod_annotation: ^2.1.1
  hooks_riverpod: ^2.3.6
  flutter_hooks: ^0.20.0
  freezed: ^2.4.1
  cloud_firestore: ^4.8.3
  logger: ^2.0.1
  overlay_support: ^2.1.0
  freezed_annotation: ^2.4.1
  firebase_core: ^2.15.0
  dartz: ^0.10.1
  json_annotation: ^4.8.1
  firebase_storage: ^11.2.5
  file_picker: ^5.2.10 
  intl: ^0.18.1
  scroll_to_index: ^3.0.1
  scrollable_positioned_list: ^0.3.8
  flutter_smart_dialog: ^4.9.4
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.12
  linkify: ^5.0.0
  flutter_social_textfield: ^0.1.2
  readmore: ^2.2.0
  better_player: ^0.0.63
  firebase_database: ^10.2.4
  wakelock: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  riverpod_generator:
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
