name: grapcoin
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  change_app_package_name: ^1.1.0
  firebase_auth: ^4.7.1
  riverpod: ^2.3.6
  flutter_riverpod: ^2.3.6
  dio: ^5.3.0
  riverpod_annotation: ^2.1.1
  hooks_riverpod: ^2.3.6
  flutter_hooks: ^0.18.6
  freezed: ^2.4.1
  cloud_firestore: ^4.8.3
  logger: ^1.4.0
  overlay_support: ^2.1.0
  freezed_annotation: ^2.4.1
  firebase_core: ^2.15.0
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
